baseURL = 'https://noteven.github.io/'
title = 'noteven but odd'
enableGitInfo = true
disableKinds = ['taxonomy', 'taxonomyTerms']
ignoreErrors = ['error-disable-taxonomy']

[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[menu]
# [[menu.before]]
[[menu.after]]
  name = "Github"
  url = "https://github.com/noteven"
  weight = 10

[[menu.after]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/nelson-bermudez-bassett/"
  weight = 20

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[params]
BookTheme = 'auto'
BookRepo = 'https://github.com/noteven/noteven.github.io'
BookFormat = '02/01/2006'
